_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/sweep_a2c.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
actor_hidden_dim1:
    value: 128
actor_hidden_dim2:
    value: 32
actor_lr:
    value: 9.055425340674996e-05
critic_hidden_dim1:
    value: 128
critic_hidden_dim2:
    value: 64
critic_lr:
    value: 0.000181034247016264
discount_factor:
    value: 0.8575961975435547
entropy_weight:
    value: 0.0002322465471477574
num_episodes:
    value: 500
seed:
    value: 456
