_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/sweep_a2c.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
actor_hidden_dim1:
    value: 128
actor_hidden_dim2:
    value: 64
actor_lr:
    value: 1.7528035599154364e-05
critic_hidden_dim1:
    value: 64
critic_hidden_dim2:
    value: 128
critic_lr:
    value: 0.008042147479340386
discount_factor:
    value: 0.8825603875815344
entropy_weight:
    value: 0.018070387465398467
num_episodes:
    value: 500
seed:
    value: 42
