_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/sweep_a2c.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
actor_hidden_dim1:
    value: 128
actor_hidden_dim2:
    value: 32
actor_lr:
    value: 0.0005799942879387574
critic_hidden_dim1:
    value: 256
critic_hidden_dim2:
    value: 32
critic_lr:
    value: 0.0004580149559385074
discount_factor:
    value: 0.9610356095081224
entropy_weight:
    value: 0.00014636597639227004
num_episodes:
    value: 500
save_per_epoch:
    value: 100
seed:
    value: 789
